### PR TITLE
Update Monitor.RegistryKey.Exists.mpx

### PR DESCRIPTION
**Pull request by degotkov**
Additional info for ClassID in the description.

### CODE REVIEW

**Comment by thekevinholman** [comment]
You should *never* target Windows Computer (it is a worst practice and can harm SCOM), so this update makes no sense.  Under what scenario would you need to target Windows Computer class?

**Comment by degotkov** [comment]
Monitoring of absence/existence of an application, for example. I don't think it should be targeted to Windows!Microsoft.Windows.Server.OperatingSystem, in the most cases an application is treated as a part of computer.

**Comment by degotkov** [comment]
Or using LocalApplication should be a more right way?

**Comment by thekevinholman** [comment]
Targeting Windows Computer for a monitoring workflow is a worst practice and should not be done unless there are specific cases where there is no other choice (I haven't seen one).  There are scenarios where large numbers of Windows Computers are hosted by a Pool or MS under specific scenarios, and we have seen this take down SCOM deployments.  In small environments, you likely would not see this.  There is nothing wrong with targeting the Windows Server OS in this scenario, but if it really bothers you just because of health rollup, you could make a generic local application class under Windows Computer for all systems in the SCOM Management group, and target all of these missing reg monitors to it?

**Comment by degotkov** [comment]
Yes, agree. Thank you.

**Pull request closed without merging**
